name: Blog Localization

on:
  # allows to manually run the job at any time
  workflow_dispatch:

  # # run on every push on the release branch
  # push:
  #   branches: [production, staging, master, refactor/**]

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - run: yarn install
        working-directory: ./generation
      - name: "Run sync command"
        working-directory: ./generation
        run: |
          yarn sync-blog
          yarn sync-template
          yarn sync-changelog

      - name: "Commit sync contents"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[GitHub Action] Sync blog contents from AFFiNE Cloud"
          file_pattern: 'content/blog/*.json content/templates/*.json'
